#!/bin/sh
set -e

case "$1" in
    configure)
        # Create the roam system user if it doesn't exist.
        if ! getent passwd roam >/dev/null 2>&1; then
            adduser --system --group --home /home/roam \
                    --shell /sbin/nologin --gecos "Read-Only Access Mode" roam
        fi
        ;;
esac

#DEBHELPER#
